//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allstate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.usertasks = new HashSet<usertask>();
        }
    
        ///<summary>User primary key</summary>
        public int id { get; set; }
        ///<summary>First name</summary>
        public string firstname { get; set; }
        ///<summary>Last name</summary>
        public string lastname { get; set; }
        ///<summary>Username</summary>
        public string username { get; set; }
        ///<summary>User password (would be hashed)</summary>
        public string password { get; set; }
        ///<summary>Date user created</summary>
        public byte[] insertdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usertask> usertasks { internal get; set; }
    }
}
